### ISSUE TITLE
Subdirectories should be standalone

### ISSUE THREAD

**Issue by friendlyanon** [PacktPublishing/CMake-Tips-and-Tricks#1]
As an example, [Chapter 1's lists file](https://github.com/PacktPublishing/CMake-Tips-and-Tricks/blob/main/chapter_1/CMakeLists.txt) should contain a call to [`cmake_minimum_required`](https://cmake.org/cmake/help/latest/command/cmake_minimum_required.html), so it is buildable on its own.

**Comment by bernedom** [comment]
Thanks for mentioning it. It's fixed now.
