### ISSUE TITLE
Usage of target_sources

### ISSUE THREAD

**Issue by friendlyanon** [PacktPublishing/CMake-Tips-and-Tricks#6]
I have noticed that the code in this repo uses `target_sources` instead of directly listing the cpp files in the target creation command.  
What is the reason for this? If you were to not use `target_sources`, then you could spare the reader from having to pay attention to another command from the get go and listing cpp files in the `add_*` calls is equivalent in behavior.

One good usecase for this command is when you have sources files that you want to [conditionally compile](https://github.com/friendlyanon/adhoc-server/blob/master/CMakeLists.txt#L24).

**Comment by bernedom** [comment]
In this repo it is not strictly necessary, but I like to have this explicitly separated. There is no compelling reason most of the time except personal preference. 

One reason is the one you mentioned about conditionally include/exclude files. I've also seen it done to separate the PRIVATE and PUBLIC files more explicitly by adding multiple calls to `target_sources`.

**Comment by friendlyanon** [comment]
Personal preference is fair. I have seen people use the command to automate adding new sources using a vim script that just appends to a sequence of `target_sources` calls.

I have not seen [`INTERFACE_SOURCES`](https://cmake.org/cmake/help/latest/prop_tgt/INTERFACE_SOURCES.html) be used, so I doubt the `PUBLIC` or `INTERFACE` modifiers are useful to beginners.

**Comment by bernedom** [comment]
Closing this issue for now, as I feel we agree that adding source files is ok both ways.
