### ISSUE TITLE
Improve cmake-format settings

### ISSUE THREAD

**Issue by friendlyanon** [PacktPublishing/CMake-Tips-and-Tricks#9]
Here is an example of weird formatting:

https://github.com/PacktPublishing/CMake-Tips-and-Tricks/blob/c4620ded5e17b85e3f940de27fa5e29e5196749d/chapter_3/hello_lib/CMakeLists.txt#L27-L28

I have not used cmake-format a lot so far, because I'm not a fan of such mistakes and they seemed to crop up frequently and custom commands always require a lot of configuring in the style yaml.

**Comment by bernedom** [comment]
We are aware of this. Unfortunately cmake-format seems to be kind of weird and we are still fiddling around with the config file to find a good compromise on the formatting. But if it does not work out we will have to go back to format manually again.

**Comment by bernedom** [comment]
Closing this issue, because cmake-format is no longer used
